# Generated by Django 3.2 on 2021-04-09 12:22

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_alter_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=datetime.datetime(2021, 4, 9, 12, 22, 1, 835367, tzinfo=utc), null=True, srid=4326),
        ),
    ]
