# Generated by Django 3.2 on 2021-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0008_alter_place_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_place', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='type_of_place',
        ),
        migrations.AddField(
            model_name='place',
            name='type_of_place',
            field=models.ManyToManyField(to='spot.TypeOfPlace'),
        ),
    ]
